version: '3.9'
name: nestjs-authentication-authorization

services:
  db:
    image: postgres:15.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgrespassword
  redis:
    image: redis:7.0.12
    ports:
      - '6379:6379'
    restart: always

volumes:
  postgres_data:
